image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - esbenp.prettier-vscode # Markdown/CommonMark linting and style checking for Visual Studio Code
    - mechatroner.rainbow-csv # Highlight columns in csv files in different colors
    - oderwat.indent-rainbow # Highlight indentation level
    - streetsidesoftware.code-spell-checker # Spelling checker for source code
    - microsoft.jupyter