image:
  file: .gitpod.Dockerfile


# Commands to start on workspace startup
tasks:
  - name: test
    init: | 
      fastp --version 
      blast --version
      spades --version 
      bowtie2 --version
      fastqc --version
      kraken2 --version


vscode:
  extensions:
    - esbenp.prettier-vscode # Markdown/CommonMark linting and style checking for Visual Studio Code
    - mechatroner.rainbow-csv # Highlight columns in csv files in different colors
    - oderwat.indent-rainbow # Highlight indentation level
    - streetsidesoftware.code-spell-checker # Spelling checker for source code
    - microsoft.jupyter